# Form implementation generated from reading ui file 'load_node.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_LoadWidget(object):
    def setupUi(self, LoadWidget):
        LoadWidget.setObjectName("LoadWidget")
        LoadWidget.resize(181, 40)
        self.valueLineEdit = QtWidgets.QLineEdit(parent=LoadWidget)
        self.valueLineEdit.setGeometry(QtCore.QRect(60, 10, 111, 20))
        self.valueLineEdit.setObjectName("valueLineEdit")
        self.valueLabel = QtWidgets.QLabel(parent=LoadWidget)
        self.valueLabel.setGeometry(QtCore.QRect(10, 10, 41, 16))
        self.valueLabel.setObjectName("valueLabel")

        self.retranslateUi(LoadWidget)
        QtCore.QMetaObject.connectSlotsByName(LoadWidget)

    def retranslateUi(self, LoadWidget):
        _translate = QtCore.QCoreApplication.translate
        LoadWidget.setWindowTitle(_translate("LoadWidget", "Form"))
        self.valueLabel.setText(_translate("LoadWidget", "Current:"))
