# Form implementation generated from reading ui file 'load_node.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_LoadWidget(object):
    def setupUi(self, LoadWidget):
        LoadWidget.setObjectName("LoadWidget")
        LoadWidget.resize(181, 101)
        self.valueLineEdit = QtWidgets.QLineEdit(parent=LoadWidget)
        self.valueLineEdit.setGeometry(QtCore.QRect(60, 70, 111, 20))
        self.valueLineEdit.setObjectName("valueLineEdit")
        self.valueLabel = QtWidgets.QLabel(parent=LoadWidget)
        self.valueLabel.setGeometry(QtCore.QRect(10, 70, 41, 16))
        self.valueLabel.setObjectName("valueLabel")
        self.nodeTypeLabel = QtWidgets.QLabel(parent=LoadWidget)
        self.nodeTypeLabel.setGeometry(QtCore.QRect(10, 10, 161, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.nodeTypeLabel.setFont(font)
        self.nodeTypeLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.nodeTypeLabel.setObjectName("nodeTypeLabel")
        self.currentRadioButton = QtWidgets.QRadioButton(parent=LoadWidget)
        self.currentRadioButton.setGeometry(QtCore.QRect(10, 40, 83, 18))
        self.currentRadioButton.setChecked(True)
        self.currentRadioButton.setObjectName("currentRadioButton")
        self.typeButtonGroup = QtWidgets.QButtonGroup(LoadWidget)
        self.typeButtonGroup.setObjectName("typeButtonGroup")
        self.typeButtonGroup.addButton(self.currentRadioButton)
        self.resistiveRadioButton = QtWidgets.QRadioButton(parent=LoadWidget)
        self.resistiveRadioButton.setGeometry(QtCore.QRect(90, 40, 83, 18))
        self.resistiveRadioButton.setObjectName("resistiveRadioButton")
        self.typeButtonGroup.addButton(self.resistiveRadioButton)

        self.retranslateUi(LoadWidget)
        QtCore.QMetaObject.connectSlotsByName(LoadWidget)

    def retranslateUi(self, LoadWidget):
        _translate = QtCore.QCoreApplication.translate
        LoadWidget.setWindowTitle(_translate("LoadWidget", "Form"))
        self.valueLabel.setText(_translate("LoadWidget", "Current:"))
        self.nodeTypeLabel.setText(_translate("LoadWidget", "Consumer"))
        self.currentRadioButton.setText(_translate("LoadWidget", "C. Current"))
        self.resistiveRadioButton.setText(_translate("LoadWidget", "Resistive"))
