# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt6 UI code generator 6.2.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(502, 348)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 40, 91, 20))
        self.label.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(80, 70, 91, 31))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(81, 91, 93, 28))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 502, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.variableUi = []

        self.setBehaviour()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Glain 0.1 alfa"))
        self.label.setText(_translate("MainWindow", "Commands:"))
        self.pushButton.setText(_translate("MainWindow", "Add"))

    def setBehaviour(self):
        self.pushButton.clicked.connect(self.slot_addCommand)

    def slot_addCommand(self):
        newButton = QtWidgets.QPushButton()
        self.variableUi.append(newButton)

        move(self.pushButton, 0, NEW_COMMAND_WIDGET_STEP)
        #increaseHeight(self.verticalLayout, NEW_COMMAND_WIDGET_STEP)
        #print(self.verticalLayout.geometry())
        #a = self.verticalLayout.geometry()
        #a.setHeight(a.height() + NEW_COMMAND_WIDGET_STEP)
        #self.verticalLayout.setGeometry(a)

        a = self.verticalLayoutWidget.geometry()
        a.setHeight(a.height() + NEW_COMMAND_WIDGET_STEP)
        self.verticalLayoutWidget.setGeometry(a)


        self.verticalLayout.addWidget(newButton)

NEW_COMMAND_WIDGET_STEP = 40

def move (qWidget, dX, dY):
    newX = qWidget.x() + dX
    newY = qWidget.y() + dY

    qWidget.move(newX, newY)

def increaseHeight (qLayout, dHeight):
    geometry = qLayout.geometry()
    print(geometry)
    geometry.setHeight(geometry.height() + dHeight)
    print(geometry)
    qLayout.setGeometry(geometry)
    print(qLayout.geometry())
